// av_botella1.gen.ts — GENERADO por gen_av.mjs. No editar a mano.
import { AvatarWindow } from "./scenes/AvatarLayer";
export const AV: AvatarWindow[] = [
  { start: 0, mode: "hidden" },
  { start: 9, mode: "cornerTR", scale: 1 },
  { start: 15, mode: "right" },
  { start: 19, mode: "cornerTR", scale: 1 },
  { start: 26, mode: "cornerBL", scale: 1.05 },
  { start: 39, mode: "hidden" },
  { start: 47, mode: "left" },
  { start: 58, mode: "cornerTL", scale: 0.95 },
  { start: 67, mode: "full" },
  { start: 84, mode: "hidden" },
  { start: 94, mode: "cornerBR", scale: 1.05 },
  { start: 104, mode: "hidden" },
  { start: 119, mode: "cornerTR", scale: 0.9 },
  { start: 148, mode: "right" },
  { start: 149, mode: "hidden" },
  { start: 158, mode: "cornerBL", scale: 1.05 },
  { start: 175, mode: "cornerTL", scale: 0.95 },
  { start: 187, mode: "left" },
  { start: 190, mode: "hidden" },
  { start: 212, mode: "cornerBR", scale: 1 },
  { start: 227, mode: "hidden" },
  { start: 268, mode: "cornerTR", scale: 0.9 },
  { start: 295, mode: "hidden" },
  { start: 342, mode: "cornerTL", scale: 0.95 },
  { start: 352, mode: "hidden" },
  { start: 361, mode: "cornerBL", scale: 1.05 },
];
