// av_botella2.gen.ts — GENERADO por gen_av.mjs. No editar a mano.
import { AvatarWindow } from "./scenes/AvatarLayer";
export const AV: AvatarWindow[] = [
  { start: 0, mode: "hidden" },
  { start: 1, mode: "hidden" },
  { start: 9, mode: "cornerTR", scale: 1 },
  { start: 23, mode: "cornerBL", scale: 1.05 },
  { start: 25, mode: "right" },
  { start: 33, mode: "hidden" },
  { start: 36, mode: "cornerBL", scale: 1.05 },
  { start: 40, mode: "hidden" },
  { start: 53, mode: "cornerTL", scale: 0.95 },
  { start: 60, mode: "hidden" },
  { start: 64, mode: "left" },
  { start: 71, mode: "cornerTL", scale: 0.95 },
  { start: 81, mode: "cornerBR", scale: 1 },
  { start: 92, mode: "hidden" },
  { start: 95, mode: "cornerTR", scale: 1 },
  { start: 100, mode: "hidden" },
  { start: 112, mode: "right" },
  { start: 118, mode: "full" },
  { start: 145, mode: "hidden" },
  { start: 164, mode: "cornerBL", scale: 1.05 },
  { start: 175, mode: "cornerTR", scale: 0.9 },
  { start: 187, mode: "hidden" },
  { start: 198, mode: "left" },
  { start: 201, mode: "hidden" },
  { start: 211, mode: "cornerBL", scale: 1.05 },
  { start: 235, mode: "cornerTL", scale: 0.95 },
  { start: 252, mode: "hidden" },
];
