// av_polvo1.gen.ts — GENERADO por gen_av.mjs. No editar a mano.
import { AvatarWindow } from "./scenes/AvatarLayer";
export const AV: AvatarWindow[] = [
  { start: 0, mode: "hidden" },
  { start: 5, mode: "hidden" },
  { start: 11, mode: "cornerTR", scale: 1 },
  { start: 17, mode: "right" },
  { start: 21, mode: "cornerBL", scale: 1.05 },
  { start: 28, mode: "left" },
  { start: 38, mode: "hidden" },
  { start: 51, mode: "cornerTR", scale: 1 },
  { start: 56, mode: "hidden" },
  { start: 63, mode: "cornerBL", scale: 1.05 },
  { start: 77, mode: "full" },
  { start: 101, mode: "hidden" },
  { start: 105, mode: "cornerTL", scale: 0.95 },
  { start: 117, mode: "hidden" },
  { start: 187, mode: "cornerTL", scale: 0.95 },
  { start: 194, mode: "hidden" },
  { start: 205, mode: "cornerBR", scale: 1 },
  { start: 219, mode: "hidden" },
  { start: 225, mode: "cornerBR", scale: 1.05 },
  { start: 235, mode: "cornerTR", scale: 0.9 },
  { start: 260, mode: "hidden" },
  { start: 289, mode: "cornerBL", scale: 1.05 },
  { start: 305, mode: "hidden" },
  { start: 329, mode: "cornerTL", scale: 0.95 },
  { start: 337, mode: "cornerTR", scale: 1 },
  { start: 356, mode: "hidden" },
  { start: 382, mode: "cornerBR", scale: 1 },
];
